export const goldProducts = [
  {
    id: "gold-necklace-1",
    name: "Traditional Gold Necklace Set",
    price: "₹ 85,000",
    imageUrl: "/gold/IMG-20250802-WA0058(1).jpg",
    imageAlt: "Traditional Gold Necklace Set with intricate design",
    description: "This exquisite necklace set is a masterpiece of traditional craftsmanship. Perfect for weddings and grand celebrations, it features intricate floral patterns and is crafted from 22-carat gold, ensuring a radiant finish and lasting value.",
  },
  {
    id: "gold-earrings-2",
    name: "Elegant Gold Earrings",
    price: "₹ 45,000",
    imageUrl: "/gold/IMG-20250802-WA0060(1).jpg",
    imageAlt: "Elegant Gold Earrings with traditional design",
    description: "Adorn your ears with these elegant gold earrings, showcasing a classic design that blends tradition with contemporary style. Made from pure 22-carat gold, they are lightweight and perfect for both formal and casual wear.",
  },
  {
    id: "gold-bracelet-3",
    name: "Designer Gold Bracelet",
    price: "₹ 65,000",
    imageUrl: "/gold/IMG-20250802-WA0056(1).jpg",
    imageAlt: "Designer Gold Bracelet with modern styling",
    description: "A stunning designer gold bracelet that makes a bold style statement. Its unique and modern design is complemented by the richness of 22-carat gold, making it a perfect accessory for the fashion-forward individual.",
  },
  {
    id: "gold-ring-4",
    name: "Royal Gold Ring",
    price: "₹ 95,000",
    imageUrl: "/gold/IMG-20250802-WA0035(1).jpg",
    imageAlt: "Royal Gold Ring with precious stones",
    description: "Feel like royalty with this magnificent gold ring. Encrusted with precious stones and crafted from 22-carat gold, this ring is a symbol of luxury and elegance, destined to be a treasured heirloom.",
  },
  {
    id: "gold-chain-5",
    name: "Classic Gold Chain",
    price: "₹ 35,000",
    imageUrl: "/gold/IMG-20250802-WA0064.jpg",
    imageAlt: "Classic Gold Chain with traditional pattern",
    description: "A timeless classic, this gold chain features a traditional pattern that exudes sophistication. Made from 22-carat gold, it's a versatile piece that can be worn alone or with a pendant for a personalized touch.",
  },
  {
    id: "gold-bangle-6",
    name: "Intricate Gold Bangle Set",
    price: "₹ 75,000",
    imageUrl: "/gold/IMG-20250802-WA0039(1).jpg",
    imageAlt: "Intricate Gold Bangle Set with detailed work",
    description: "This set of intricately designed gold bangles is a testament to the skill of our artisans. Crafted from 22-carat gold, these bangles are perfect for adding a touch of tradition and opulence to any outfit.",
  },
  {
    id: "gold-pendant-7",
    name: "Floral Gold Pendant",
    price: "₹ 28,000",
    imageUrl: "/gold/IMG-20250802-WA0013.jpg",
    imageAlt: "Floral Gold Pendant with delicate design",
    description: "A delicate floral gold pendant that captures the beauty of nature. This charming piece is crafted from 22-carat gold and is perfect for everyday wear, adding a subtle touch of elegance to your look.",
  },
  {
    id: "gold-mangalsutra-8",
    name: "Designer Mangalsutra",
    price: "₹ 55,000",
    imageUrl: "/gold/IMG-20250802-WA0031.jpg",
    imageAlt: "Designer Mangalsutra with modern touch",
    description: "A modern take on the traditional mangalsutra, this piece combines sacred symbolism with contemporary design. Crafted in 22-carat gold, it's a beautiful and meaningful accessory for the modern bride.",
  },
];

export const silverProducts = [
  {
    id: "silver-ring-1",
    name: "Sterling Silver Ring",
    price: "₹ 8,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Sterling Silver Ring with elegant design",
    description: "An elegant sterling silver ring that combines simplicity and style. Its timeless design makes it a versatile accessory for any occasion, adding a touch of sophistication to your look.",
  },
  {
    id: "silver-pendant-2",
    name: "Delicate Silver Pendant",
    price: "₹ 12,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Delicate Silver Pendant with intricate details",
    description: "This delicate silver pendant is a work of art, featuring intricate details that showcase exceptional craftsmanship. It's a subtle yet stunning piece that will complement any outfit.",
  },
  {
    id: "silver-anklet-3",
    name: "Artisan Silver Anklet",
    price: "₹ 5,500",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Artisan Silver Anklet with traditional pattern",
    description: "Adorn your feet with this beautiful artisan silver anklet. Featuring a traditional pattern, it's a charming accessory that adds a touch of ethnic grace to your style.",
  },
  {
    id: "silver-earrings-4",
    name: "Bohemian Silver Earrings",
    price: "₹ 7,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Bohemian Silver Earrings with unique style",
    description: "Express your free spirit with these bohemian silver earrings. Their unique style and intricate design make them a perfect accessory for a standout, fashionable look.",
  },
  {
    id: "silver-bracelet-5",
    name: "Chunky Silver Bracelet",
    price: "₹ 15,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Chunky Silver Bracelet with modern design",
    description: "Make a statement with this chunky silver bracelet. Its bold and modern design is perfect for those who love to express their individuality through their accessories.",
  },
  {
    id: "silver-chain-6",
    name: "Minimalist Silver Chain",
    price: "₹ 9,500",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Minimalist Silver Chain with clean lines",
    description: "A minimalist silver chain that is both elegant and versatile. Its clean lines and simple design make it a perfect everyday accessory that can be worn alone or layered.",
  },
  {
    id: "silver-toe-ring-7",
    name: "Traditional Toe Ring Set",
    price: "₹ 3,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Traditional Toe Ring Set with cultural significance",
    description: "Embrace tradition with this beautiful set of silver toe rings. Their classic design holds cultural significance and adds a touch of ethnic charm to your feet.",
  },
  {
    id: "silver-kada-8",
    name: "Engraved Silver Kada",
    price: "₹ 18,000",
    imageUrl: "/silver/IMG-20250802-WA0028.jpg",
    imageAlt: "Engraved Silver Kada with detailed work",
    description: "A beautifully engraved silver kada that showcases exquisite craftsmanship. This statement piece is perfect for adding a touch of royalty and tradition to your ensemble.",
  },
];
